export const userInputs = [
  {
    id: 1,
    label: 'Username',
    type: 'text',
    name: 'username',
    placeholder: 'john_doe',
  },
  {
    id: 2,
    label: 'Name and surname',
    type: 'text',
    name: 'name',
    placeholder: 'John Doe',
  },
  {
    id: 3,
    label: 'Email',
    type: 'mail',
    name: 'email',
    placeholder: 'olagokeabel@gmail.com',
  },
  {
    id: 4,
    label: 'Phone',
    type: 'text',
    name: 'phone',
    placeholder: '+2348066181836',
  },
  {
    id: 5,
    label: 'Password',
    type: 'password',
    name: 'password',
  },
  {
    id: 6,
    label: 'Address',
    type: 'text',
    name: 'address',
    placeholder: 'Elton St. 216 NewYork',
  },
  {
    id: 7,
    label: 'Country',
    type: 'text',
    name: 'country',
    placeholder: 'USA',
  },
  {
    id: 8,
    label: 'Country',
    type: 'text',
    name: 'country',
    placeholder: 'USA',
  },
];

export const productInputs = [
  {
    id: 1,
    label: 'Title',
    type: 'text',
    name: 'title',
    placeholder: 'Apple Macbook Pro',
  },
  {
    id: 2,
    label: 'Description',
    type: 'text',
    name: 'description',
    placeholder: 'Description',
  },
  {
    id: 3,
    label: 'Category',
    type: 'text',
    name: 'category',
    placeholder: 'computer',
  },
  {
    id: 4,
    label: 'Price',
    type: 'text',
    name: 'price',
    placeholder: '100',
  },
  {
    id: 5,
    label: 'Description',
    type: 'text',
    name: 'description',
    placeholder: 'Description',
  },
];
